version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4
    platform: linux/arm64  # For Apple Silicon (M1/M2/M3)
    command: jekyll serve --watch --force_polling --livereload
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
